version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgre-teachy
    environment:
      POSTGRES_DB: teachy
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: